### ISSUE TITLE
Unable to import module as directory

### ISSUE THREAD

**Issue by soanvig** [frostney/rollup-plugin-alias#37]
I cannot load modules as `import x from '@/directory'` (where `directory` contains `index.js`).

My config:

```
alias({
    '@': path.join(__dirname, './src')
})
```

**What doesn't work**
`import x from '@/directory'`

**What works**
`import x from './directory'`
`import x from '@/directory/index.js'`

**Comment by lduoduo** [comment]
same issue as this, please take a look in, thanks!

**Comment by soanvig** [comment]
I did quick look into the code and it seems to be working only with files. This may be greater modification, than I thought. Unfortunately I have no idea of rollup and rollup plugin system.

I am wondering, if behaviour:
```
if (isDirectory(path)) {
   path + '/index.js';
}
```
would do the trick. I am going to experiment a little. But - for me at least - it looks like hackish solution.

**Comment by soanvig** [comment]
@lduoduo you may be interested in my PR.

**Comment by frostney** [comment]
Thank you for writing up this issue, we had a similar pull request some time ago: https://github.com/rollup/rollup-plugin-alias/pull/25

The responsibility of this plugin is to only handle aliases, not to handle Node's resolution mechanism. If you would like to use that functionality, please use `rollup-plugin-node-resolve` in combination with this plugin.

Please feel free to re-open if you think this is not resolved.

**Comment by soanvig** [comment]
Can you provide us with working example? Because AFAIR it's impossible to combine these two modules, to achieve appropriate effect.
I strongly agree with your statement of plugin's responsibility though.

**Comment by dudiq** [comment]
as example:
```
alias({
     '@': path.join(__dirname, './src'),
     resolve: ['.js', '/index.js'],
   }),
```

**Comment by wickkidd** [comment]
### Hack
I got it working for the `/index.js` case by adding the following after this line https://github.com/rollup/rollup-plugin-alias/blob/master/src/index.js#L80
```javascript
else if (fs.existsSync(path.resolve(filePath, 'index.js'))) {
          updatedId = filePath + '/index.js'
        }
```

Before you get too excited, this _only_ handles that case, so if your needs are more complex (`index.ts` for example) this won't be enough.

### Thoughts
After reading the issues here, [on rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve/issues/152), and [rollup](https://github.com/rollup/rollup/issues/2609#issuecomment-449648787) it seems that we're basically in a stalemate. Both plugin authors assert that their plugin isn't responsible for the duties (even partially so) of the other and I agree with them. Doing so would introduce more complexity and hence more opportunity for bugs–not to mention a higher maintenance cost. The root cause seems to be due to rollup not passing the module id to other plugins once it is resolved.

While I think that rollup having some mechanism for passing the module id to other plugins is likely the better way to go, in the meantime people who use this for their projects have to get things done and so hacks like mine above wind up being the (hopefully temporary) compromise.
